version: "3.8"
services:
  backend:
    image: "krasy8/springboot-react-fullstack:15.4.2021.23.15.17"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
