version: "3.8"
services:
  backend:
    image: "krasy8/springboot-react-fullstack:16.4.2021.10.13.0"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
